# Golang CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8

    working_directory: /go/src/github.com/fresh8/asprom
    steps:
      - checkout
      - run: go build

  deployment:
    tag:
      tag: /v[0-9]+(\.[0-9]+)*(-.*)*/
      owner: user
      commands:
        - curl -sL https://git.io/goreleaser | bash
